disabled_rules:
    - function_body_length
    - type_body_length
    - file_length
    - force_cast
    - force_try
    - identifier_name
    - type_name
    - todo
    - large_tuple
    - notification_center_detachment
    - cyclomatic_complexity
    - closure_parameter_position
    - weak_delegate
    - inclusive_language
    - class_delegate_protocol
    - multiple_closures_with_trailing_closure
    - nesting
    - function_parameter_count
    - xctfail_message
    
included:
    - Source
    - Tests

# In order to deal with the huge number of violations, first set
# very high limits then iteratively reduce the limits and resolve
# the few violations. Repeat this until we find suitable limits.

line_length:
    warning: 500
    error: 500
