env:
  global:
  - secure: DUTI6xnk6emxAGtabSBfFH5QO6jxkRgjCWZp6fnXGrT125ZJ1Gdmf7+O9Gm/qfv9g2zUwjAnptgXUPvPT3xkdB256Ev7eLok9yTwErRd4vubbmxxu7+EqavYg1kQtdb6UStZ5c1Yz/S2mlqOxG5KMQxom80WU9Cfdq096q8hfeJ25hsNdoKBs1EN4Dyb8VxDdTRBHbADE8prqEDtNEprLEYBKzNkH9EbvR/1sPpZ6tsWFKG5mLNifaV/BDfogoFhsgex5EAibpUhXgC4L9zsJMk0Xh8iUOXNkxp7dsOxMeazEtfnUxB26nXUaH2aSopnahmznEtmsKWxLrUheKVKX8rms5fAWTvC8O7p5KYmijzckWGsLK02xRa2lFd71Muw73ZTHL3fLwRJKF7JuU1Aw9bWcVBVjh6rRVaXJloyvJ5rlqvlCWLbUmAJp3QeBJC8MYDenT2G0RIfGEAitNI91IleJrRkX9jmgdzTwa0q+37imIk/H0F4joG4RxXYIx/OU7a95cYvR2pZ9I7jmaRYMlK9jR9huykoP4J2HdsKvkIZhvaIc/wh37B2Pe+tm42vZtcpu3Axym078T5oBs2NDrBYKX0QEpG+eFNA7nshpcPkKvSh2BJN/GFEPgbuSbuzFPYUTmhGOEsM7g1vIsds+rb3zs5/wf48tTiBhPBYh00=
  - secure: oae/cY504FC44CSMQjvr4jKxHTS0ItUaSk5wR3cQ8C0X6xkDS7wr/xDIncVt0+pClj7jPmXeuzByjKitHOaLasa+HmYn+lU1d9KBvJgnp3qKr1fAQhf49YHEtES5b8+8ON4BNQduFnm6iMiKRlimMwHsEa+IvcHUuebr5SCo7ejZERTSecdejTFYyltibNrwZF+wcYK9ztRMNasQyzVcaWG2/Y9t+Yj8NeNiA9gNFFJw6RRQUmUz4zbFcvq/guQoIuYT6erI3pKBZWGNv4Usv8ocp+soYTScEs5onsoBU/896oeKgZtPDW4qC8DWHri+fm7J5pTTjv/SYmFBFrTxZne28xsM35+T//tJG4Qm+TTX1Jo4qM/q4mGtpHkZNgG+jFibgzpdjgsygTRS6Sqx1HAMzyeXVtR/gWLNMnEe1+F4uJJEPf96XG1uACiEDv2LZHsI08QeMKTHI8/HTah+PXnJS99AeuoXdTHy8kLDmx32CfxOKZKdCdJvmkrZLJPZQT9wEcBOomw327hTEW51rPByJFp8dopgFwR3eUl4a+IscP2VNXig/X5FY6GGzq4D7/FieCgz3NIvbUDZEUmqWTbS5bY5771r1Gv1msvO5l8AXzvVGe23sWRj4wswPFaFxgPtB1WzB8sR9Ouaz8K0KCsTkjlD1z4Ho7O/nJs2hk8=

language: ruby
rvm: 2.4.0

notifications:
  email: false

cache: bundler

branches:
  only:
    - develop
    - master

install:
  - bundle install
  - curl -O https://raw.githubusercontent.com/wireapp/wire-ios-shared-resources/master/Dangerfile

script:
  - set -o pipefail
  - bundle exec danger
