name: review PR by Zenkins v0.1.3

on: 
  issue_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
jobs:
  review:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    env:
      ADMINS: ('billypchan' 'marcoconti83' 'typfel' 'johnxnguyen' 'David-Henner' 'KaterinaWire' 'sb88k' 'agisilaos')

    steps:
# TODO: only guard when issue_comment
#       - name: guard for pull requests
#         if: ${{ !github.event.issue.pull_request }}
#         run: exit 1
#       - name: guard for magic spell
#         if: ${{ github.event.comment.body != '@zenkins review' }}
#         run: exit 1

      # workaround of unable to include : in string
      - name: guard for title
        if: ${{ !(startsWith(github.event.pull_request.title, 'chore') && endsWith(github.event.pull_request.title, 'bump components SQPIT-776')) }}
        run: |
          echo "github: ${{ github }}"
          echo "title not match. Exit. Title is ${{ github.event.issue.title }}"
          exit 0

      - name: guard for admins
        run: |
          admins=${{ env.ADMINS }}
          adminFound=0
          for admin in ${admins[*]}
          do
            if [[ "$admin" == "${{ github.actor }}" ]]; then
              echo ${{ github.actor }} is allowed for releasing
              adminFound=1
            fi
          done
          if [ $adminFound = 0 ]; then
            echo ${{ github.actor }} is not allowed for releasing
            exit 1
          fi

      - name: Review bump components PR
        run: |
          # auth with zenkins to prevent self approval not allowed issue
          # TODO: guard for Cartfile is not empty
          echo ${{ secrets.ZENKINS_TOKEN }} > .githubtoken
          gh auth login --with-token < .githubtoken
          gh pr review ${{ github.event.pull_request.number }} --approve -R wireapp/${{ github.event.repository.name }}

          rm .githubtoken
