# This is a basic workflow to help you get started with Actions

name: test get next version

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: get latest release version
      id: latestVersion
      run: |
        LATEST_VERSION=$(curl --silent "https://api.github.com/repos/wireapp/wire-ios-sync-engine/releases/latest" | jq -r .tag_name) || true
        echo $LATEST_VERSION
        echo "::set-output name=LATEST_VERSION::$LATEST_VERSION"
    - name: Bump release version
      id: bump_version
      uses: christian-draeger/increment-semantic-version@1.0.2
      with:
        current-version: ${{ steps.latestVersion.outputs.LATEST_VERSION }}
        version-fragment: 'feature'
    - name: Do something with your bumped release version
      run: echo ${{ steps.bump_version.outputs.next-version }}
